---
kind: Simple
apiVersion: k3d.io/v1alpha5
metadata:
  name: k3s-local
servers: 1
agents: 1
kubeAPI:
  hostIP: 127.0.0.1
  hostPort: '6443'
image: rancher/k3s:v1.29.6-k3s1
volumes:
  - volume: "${K3D_PROJECT_PATH}/manifests/:/var/lib/rancher/k3s/server/manifests/k3s-local/"
    nodeFilters:
      - server:*
ports:
  - port: 127.0.0.1:80:80
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
  runtime:
    serversMemory: 2G
    agentsMemory: 4G