name: Test
on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup k3d
      uses: rinx/setup-k3d@v0.0.4
      with:
        skipClusterCreation: true
        version: v5.6.3

    - name: Install grpcurl
      run: |
        #!/bin/bash

        # Install grpcurl if not installed
        if ! command -v grpcurl >/dev/null 2>&1; then
            curl -sSL "https://github.com/fullstorydev/grpcurl/releases/download/v1.8.6/grpcurl_1.8.6_linux_x86_64.tar.gz" | tar -xz -C /usr/local/bin
        fi

    - run: make provision

    - run: sleep 15 # In GH Actions seems to be the pulling a bit slow, probably low resources specs

    - name: Check gRPC 
      run: make test